name = "Risor"
grammar = "risor"
path_suffixes = ["risor"]
first_line_pattern = "^#!.*\\brisor\\b"
line_comments = ["// "]
tab_size = 2
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]

# Indent if the line starts with a keyword that must be followed by one or more parameters *or*
# if the line starts and ends with `begin` or `else` *or*
# if the line ends with an opening parentheses or a backslash.
increase_indent_pattern = "^\\s*(func|if|else\\s+if|while|for|switch|case)\\b|^\\s*(begin|else)\\s*$|[(\\\\]\\s*$"

# Dedent if the line starts with a keyword that ends a block or with a closing parentheses.
# decrease_indent_pattern = "^\\s*(else|case|end)\\b|^\\s*\\)"
