id = "risor"
name = "Risor"
version = "0.0.2"
schema_version = 1
authors = ["Sergio Rubio <rubiojr@rbel.co>"]
description = "Risor language extension"
repository = "https://github.com/rubiojr/zed-risor"
path_suffixes = ["risor", "rsr"]

[grammars.risor]
repository = "https://github.com/applejag/tree-sitter-risor"
rev = "bec6f2e385597d0cae55b38f54515eee5f0ebffd"
